Python path configuration:
  PYTHONHOME = '/home/credcnqu/virtualenv/credalarm/2.7'
  PYTHONPATH = '.:/home/credcnqu/credalarm/'
  program name = '/home/credcnqu/virtualenv/credalarm/3.9/bin/python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/home/credcnqu/virtualenv/credalarm/3.9/bin/python'
  sys.base_prefix = '/home/credcnqu/virtualenv/credalarm/2.7'
  sys.base_exec_prefix = '/home/credcnqu/virtualenv/credalarm/2.7'
  sys.platlibdir = 'lib64'
  sys.executable = '/home/credcnqu/virtualenv/credalarm/3.9/bin/python'
  sys.prefix = '/home/credcnqu/virtualenv/credalarm/2.7'
  sys.exec_prefix = '/home/credcnqu/virtualenv/credalarm/2.7'
  sys.path = [
    '.',
    '/home/credcnqu/credalarm/',
    '/home/credcnqu/virtualenv/credalarm/2.7/lib64/python39.zip',
    '/home/credcnqu/virtualenv/credalarm/2.7/lib64/python3.9',
    '/home/credcnqu/virtualenv/credalarm/2.7/lib64/python3.9/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002ad2645ed2c0 (most recent call first):
<no Python frame>
Python path configuration:
  PYTHONHOME = '/home/credcnqu/virtualenv/credalarm/2.7'
  PYTHONPATH = '.:/home/credcnqu/credalarm/'
  program name = '/home/credcnqu/virtualenv/credalarm/3.9/bin/python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/home/credcnqu/virtualenv/credalarm/3.9/bin/python'
  sys.base_prefix = '/home/credcnqu/virtualenv/credalarm/2.7'
  sys.base_exec_prefix = '/home/credcnqu/virtualenv/credalarm/2.7'
  sys.platlibdir = 'lib64'
  sys.executable = '/home/credcnqu/virtualenv/credalarm/3.9/bin/python'
  sys.prefix = '/home/credcnqu/virtualenv/credalarm/2.7'
  sys.exec_prefix = '/home/credcnqu/virtualenv/credalarm/2.7'
  sys.path = [
    '.',
    '/home/credcnqu/credalarm/',
    '/home/credcnqu/virtualenv/credalarm/2.7/lib64/python39.zip',
    '/home/credcnqu/virtualenv/credalarm/2.7/lib64/python3.9',
    '/home/credcnqu/virtualenv/credalarm/2.7/lib64/python3.9/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002ab9aac332c0 (most recent call first):
<no Python frame>
Python path configuration:
  PYTHONHOME = '/home/credcnqu/virtualenv/credalarm/2.7'
  PYTHONPATH = '.:/home/credcnqu/credalarm/'
  program name = '/home/credcnqu/virtualenv/credalarm/3.9/bin/python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/home/credcnqu/virtualenv/credalarm/3.9/bin/python'
  sys.base_prefix = '/home/credcnqu/virtualenv/credalarm/2.7'
  sys.base_exec_prefix = '/home/credcnqu/virtualenv/credalarm/2.7'
  sys.platlibdir = 'lib64'
  sys.executable = '/home/credcnqu/virtualenv/credalarm/3.9/bin/python'
  sys.prefix = '/home/credcnqu/virtualenv/credalarm/2.7'
  sys.exec_prefix = '/home/credcnqu/virtualenv/credalarm/2.7'
  sys.path = [
    '.',
    '/home/credcnqu/credalarm/',
    '/home/credcnqu/virtualenv/credalarm/2.7/lib64/python39.zip',
    '/home/credcnqu/virtualenv/credalarm/2.7/lib64/python3.9',
    '/home/credcnqu/virtualenv/credalarm/2.7/lib64/python3.9/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002b1c2f6602c0 (most recent call first):
<no Python frame>
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from flask import Flask, render_template, request, redirect, url_for
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 11, in <module>
    db = SQLAlchemy(app)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
    _include_sqlalchemy(self, query_class)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
    for key in module.__all__:
AttributeError: module 'sqlalchemy' has no attribute '__all__'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 11, in <module>
    db = SQLAlchemy(app)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
    _include_sqlalchemy(self, query_class)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
    for key in module.__all__:
AttributeError: module 'sqlalchemy' has no attribute '__all__'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 11, in <module>
    db = SQLAlchemy(app)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
    _include_sqlalchemy(self, query_class)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
    for key in module.__all__:
AttributeError: module 'sqlalchemy' has no attribute '__all__'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 11, in <module>
    db = SQLAlchemy(app)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
    _include_sqlalchemy(self, query_class)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
    for key in module.__all__:
AttributeError: module 'sqlalchemy' has no attribute '__all__'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 11, in <module>
    db = SQLAlchemy(app)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
    _include_sqlalchemy(self, query_class)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
    for key in module.__all__:
AttributeError: module 'sqlalchemy' has no attribute '__all__'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 11, in <module>
    db = SQLAlchemy(app)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
    _include_sqlalchemy(self, query_class)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
    for key in module.__all__:
AttributeError: module 'sqlalchemy' has no attribute '__all__'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 11, in <module>
    db = SQLAlchemy(app)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
    _include_sqlalchemy(self, query_class)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
    for key in module.__all__:
AttributeError: module 'sqlalchemy' has no attribute '__all__'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 11, in <module>
    db = SQLAlchemy(app)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
    _include_sqlalchemy(self, query_class)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
    for key in module.__all__:
AttributeError: module 'sqlalchemy' has no attribute '__all__'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'app.py')
  File "/opt/alt/python39/lib64/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 11, in <module>
    db = SQLAlchemy(app)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
    _include_sqlalchemy(self, query_class)
  File "/home/credcnqu/virtualenv/credalarm/3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
    for key in module.__all__:
AttributeError: module 'sqlalchemy' has no attribute '__all__'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 9, in <module>
    application = wsgi.application
AttributeError: module 'wsgi' has no attribute 'application'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 9, in <module>
    application = wsgi.application
AttributeError: module 'wsgi' has no attribute 'application'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 9, in <module>
    application = wsgi.application
AttributeError: module 'wsgi' has no attribute 'application'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 9, in <module>
    application = wsgi.application
AttributeError: module 'wsgi' has no attribute 'application'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 9, in <module>
    application = wsgi.application
AttributeError: module 'wsgi' has no attribute 'application'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 9, in <module>
    application = wsgi.application
AttributeError: module 'wsgi' has no attribute 'application'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 9, in <module>
    application = wsgi.application
AttributeError: module 'wsgi' has no attribute 'application'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 9, in <module>
    application = wsgi.application
AttributeError: module 'wsgi' has no attribute 'application'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 9, in <module>
    application = wsgi.application
AttributeError: module 'wsgi' has no attribute 'application'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 9, in <module>
    application = wsgi.application
AttributeError: module 'wsgi' has no attribute 'application'
Traceback (most recent call last):
  File "/home/credcnqu/credalarm/passenger_wsgi.py", line 9, in <module>
    application = wsgi.application
AttributeError: module 'wsgi' has no attribute 'application'
2023-04-15 01:14:52.668290 [ERROR] [UID:6764][0] wsgiHandler getApp [application] failed, pApp=(nil).
[ERROR] [UID:6764][4113465] wsgiHandler getApp [application] failed, pApp=(nil).
AttributeError: module 'passenger_wsgi' has no attribute 'application'
[ERROR] [UID:6764][4113465] wsgiHandler getApp [application] failed, pApp=(nil).
AttributeError: module 'passenger_wsgi' has no attribute 'application'
